### ISSUE TITLE
Kanban board review

### ISSUE THREAD

**Issue by jlvFlores** [jlvFlores/RoR-recipe-app#11]
## Hello future reviewer 👋

Here is the link to our [Kanban board](https://github.com/jlvFlores/RoR-recipe-app/projects/1).
We are a team of three, that includes:
- [Federica Ulzurrun](https://github.com/federicaulzurrun)
- [Kola Kolade](https://github.com/kkolade)
- and me [Jose Luis Vazquez](https://github.com/jlvFlores)

### things that have changed since the last review:
- Added two more cards for each required page. (Test and N+1)
- Added a card "Create navbar" and notes to each list page to so that our team knows when to add a route to their page and avoid breaking the DRY principle by not making various navbars.
- Updated card requirements to include notes that will remind us to follow the wireframe template on those pages that have a requiered wireframe template.

**Comment by Owusu-Desmond** [comment]
Hi @jlvFlores, @kkolade and @federicaulzurrun  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
📌 Great working on the set up of the project board ✅

## Required Changes ♻️
_Check the comments under the review._

- [x] From the project requirement, Each task should be a separate card that has a descriptive title, number of points and description of the task but currently, Your [Recipe app project requirement tasks](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements) below does not have a separate card in your project board so make sure that you create a separate card for them in your project board.
  - You should follow the layout of the wireframes provided. You should personalize the rest of the design including colors, typographies, spacings, etc.
  - Make sure there are no N+1 queries happening.
  - Create a navigation menu that allows users to open all of the pages you created.
  - Write unit and integration tests

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OyePriscilla** [comment]
Hi @jlvFlores, @kkolade and @federicaulzurrun 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Added tasks for navigation menu, unit and integration tests, and N+1 queries ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
